on: [pull_request, push]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  distribution: zulu
                  java-version: '8'
                  cache: 'gradle'
            - name: Change wrapper permissions
              run: chmod +x ./gradlew
            - run: ./gradlew ktlintCheck
